version: "3"

services:
  broker-service:
    build:
      context: ../broker-service
      dockerfile: ../broker-service/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - WEB_PORT=8080
